language: node_js
node_js:
  - '0.12'
  - '4.2'
  - 'stable'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5
  - brew update
  - brew install composer
  - php --version
  - composer --version
install:
  - cd twig-pl-core
  - npm install # we have a `postinstall` hook that runs `composer install`
script:
  - pwd
  - npm test
